---

- name: Set variables
  set_fact:
    git_url: "https://github.com/Neurita/pypes.git"
    git_dir: "{{ neuro_projects_dir }}/neuro_pypes"
    git_tag: "master"

- name: neuro_pypes | Set variables
  set_fact:
    neuro_pypes_dir: "{{ git_dir }}"

- name: neuro_pypes | Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ git_dir }}"

- name: neuro_pypes | Clone repository
  git:
    repo: "{{ git_url }}"
    dest: "{{ git_dir }}"
    version: "{{ git_tag }}"
    recursive: no
    accept_hostkey: yes

- name: neuro_docker | Set variables
  set_fact:
    git_url: "https://github.com/Neurita/neuro_docker.git"
    git_dir: "{{ neuro_projects_dir }}/neuro_docker"
    git_tag: "master"

- name: neuro_docker | Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ git_dir }}"

- name: neuro_docker | Clone repository
  git:
    repo: "{{ git_url }}"
    dest: "{{ git_dir }}"
    version: "{{ git_tag }}"
    recursive: no
    accept_hostkey: yes

- name: std_brains | Set variables
  set_fact:
    git_url: "https://github.com/Neurita/std_brains.git"
    git_dir: "{{ neuro_projects_dir }}/neuro/std_brains"
    git_tag: "master"

- name: std_brains | Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ git_dir }}"

- name: std_brains | Clone repository
  git:
    repo: "{{ git_url }}"
    accept_hostkey: yes
    dest: "{{ git_dir }}"
    recursive: no
    version: "{{ git_tag }}"
