---

n_cpus: 1

cleanup_sources: False

local_downloads_dir: '{{ playbook_dir }}/downloads'

ants_build_dir: "{{ soft_dir }}/ants/build"

default_gcc: "gcc-6"
default_gpp: "g++-6"

target_bashrc_file: '{{ neuro_bash_file }}'
